In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("data/reddit_opinion_climate_change.csv")

,comment_id,score,self_text,subreddit,created_time,post_id,author_name,controversiality,ups,downs,...,user_link_karma,user_comment_karma,user_total_karma,post_score,post_self_text,post_title,post_upvote_ratio,post_thumbs_ups,post_total_awards_received,post_created_time
0,nwp6q7t,1,We import the poorest of the poor so they can ...,conspiracy,2025-12-30 08:30:57,1pzbymv,roybringus,0,1,0,...,158.0,74179.0,74337.0,5,According to the Center for Immigration studie...,"The Minnesota Fraud Isn’t Just The Autism , Ch...",0.86,5,0,2025-12-30 07:37:15
1,nwp6p97,1,"Finally a decent map of Europe, where not hal...",europe,2025-12-30 08:30:42,1pz7diw,Utstein,0,1,0,...,1512.0,27846.0,29358.0,3,NaN,Europe if all the glaciers melted – new cities...,1.00,3,0,2025-12-30 03:36:47
2,nwp6eoj,1,&gt; Fundamentally the reason why China will n...,changemyview,2025-12-30 08:27:54,1pz1hqm,ThePoorsDelendaEst,0,1,0,...,4.0,838.0,842.0,0,There is a high likelihood that in a few years...,CMV: If war were to begin in Taiwan against Ch...,0.39,0,0,2025-12-29 23:18:01
3,nwp66r8,1,Evs have been around for 15 years,energy,2025-12-30 08:25:52,1pyqn2u,that_dutch_dude,0,1,0,...,936.0,237609.0,238545.0,561,NaN,Do electric vehicles really catch fire more th...,0.96,561,0,2025-12-29 16:26:10
4,nwp62hy,1,"Meanwhile, democrats are always praised for vo...",conspiracy,2025-12-30 08:24:47,1pzbymv,InfowarriorKat,0,1,0,...,9915.0,144896.0,154811.0,5,According to the Center for Immigration studie...,"The Minnesota Fraud Isn’t Just The Autism , Ch...",0.86,5,0,2025-12-30 07:37:15

In [4]:
df.head()

,comment_id,score,self_text,subreddit,created_time,post_id,author_name,controversiality,ups,downs,...,user_link_karma,user_comment_karma,user_total_karma,post_score,post_self_text,post_title,post_upvote_ratio,post_thumbs_ups,post_total_awards_received,post_created_time
0,nwp6q7t,1,We import the poorest of the poor so they can ...,conspiracy,2025-12-30 08:30:57,1pzbymv,roybringus,0,1,0,...,158.0,74179.0,74337.0,5,According to the Center for Immigration studie...,"The Minnesota Fraud Isn’t Just The Autism , Ch...",0.86,5,0,2025-12-30 07:37:15
1,nwp6p97,1,"Finally a decent map of Europe, where not hal...",europe,2025-12-30 08:30:42,1pz7diw,Utstein,0,1,0,...,1512.0,27846.0,29358.0,3,NaN,Europe if all the glaciers melted – new cities...,1.00,3,0,2025-12-30 03:36:47
2,nwp6eoj,1,&gt; Fundamentally the reason why China will n...,changemyview,2025-12-30 08:27:54,1pz1hqm,ThePoorsDelendaEst,0,1,0,...,4.0,838.0,842.0,0,There is a high likelihood that in a few years...,CMV: If war were to begin in Taiwan against Ch...,0.39,0,0,2025-12-29 23:18:01
3,nwp66r8,1,Evs have been around for 15 years,energy,2025-12-30 08:25:52,1pyqn2u,that_dutch_dude,0,1,0,...,936.0,237609.0,238545.0,561,NaN,Do electric vehicles really catch fire more th...,0.96,561,0,2025-12-29 16:26:10
4,nwp62hy,1,"Meanwhile, democrats are always praised for vo...",conspiracy,2025-12-30 08:24:47,1pzbymv,InfowarriorKat,0,1,0,...,9915.0,144896.0,154811.0,5,According to the Center for Immigration studie...,"The Minnesota Fraud Isn’t Just The Autism , Ch...",0.86,5,0,2025-12-30 07:37:15

## Columns

In [8]:
df[[
    "comment_id",
    "score",
    "self_text",
    "subreddit",
    "created_time",
    "controversiality",
    "ups",
    "downs"
]].head()

,comment_id,score,self_text,subreddit,created_time,controversiality,ups,downs
0,nwp6q7t,1,We import the poorest of the poor so they can ...,conspiracy,2025-12-30 08:30:57,0,1,0
1,nwp6p97,1,"Finally a decent map of Europe, where not hal...",europe,2025-12-30 08:30:42,0,1,0
2,nwp6eoj,1,&gt; Fundamentally the reason why China will n...,changemyview,2025-12-30 08:27:54,0,1,0
3,nwp66r8,1,Evs have been around for 15 years,energy,2025-12-30 08:25:52,0,1,0
4,nwp62hy,1,"Meanwhile, democrats are always praised for vo...",conspiracy,2025-12-30 08:24:47,0,1,0

In [9]:
df[[
    "author_name",
    "user_is_verified",
    "user_account_created_time",
    "user_awardee_karma",
    "user_awarder_karma",
    "user_link_karma",
    "user_comment_karma",
    "user_total_karma"
]].head()

,author_name,user_is_verified,user_account_created_time,user_awardee_karma,user_awarder_karma,user_link_karma,user_comment_karma,user_total_karma
0,roybringus,True,2013-01-10 03:54:20,0.0,0.0,158.0,74179.0,74337.0
1,Utstein,True,2024-08-20 17:27:19,0.0,0.0,1512.0,27846.0,29358.0
2,ThePoorsDelendaEst,True,2025-11-02 14:51:20,0.0,0.0,4.0,838.0,842.0
3,that_dutch_dude,True,2019-05-01 08:26:42,0.0,0.0,936.0,237609.0,238545.0
4,InfowarriorKat,True,2020-02-06 16:25:28,0.0,0.0,9915.0,144896.0,154811.0

In [11]:
df[[
    "post_id",
    "post_score",
    "post_self_text",
    "post_title",
    "post_upvote_ratio",
    "post_thumbs_ups",
    "post_total_awards_received",
    "post_created_time"
]].head()

,post_id,post_score,post_self_text,post_title,post_upvote_ratio,post_thumbs_ups,post_total_awards_received,post_created_time
0,1pzbymv,5,According to the Center for Immigration studie...,"The Minnesota Fraud Isn’t Just The Autism , Ch...",0.86,5,0,2025-12-30 07:37:15
1,1pz7diw,3,NaN,Europe if all the glaciers melted – new cities...,1.00,3,0,2025-12-30 03:36:47
2,1pz1hqm,0,There is a high likelihood that in a few years...,CMV: If war were to begin in Taiwan against Ch...,0.39,0,0,2025-12-29 23:18:01
3,1pyqn2u,561,NaN,Do electric vehicles really catch fire more th...,0.96,561,0,2025-12-29 16:26:10
4,1pzbymv,5,According to the Center for Immigration studie...,"The Minnesota Fraud Isn’t Just The Autism , Ch...",0.86,5,0,2025-12-30 07:37:15

### Dati del Commento

* **comment_id**: ID del commento
* **score**: Punteggio (differenza tra upvote e downvote)
* **self_text**: Testo del commento
* **subreddit**: Nome della comunità (subreddit) in cui è stato postato
* **created_time**: Orario di creazione del commento
* **controversiality**: Grado di controversia (basato sul rapporto tra voti positivi e negativi)
* **ups**: Numero di voti positivi (upvotes)
* **downs**: Numero di voti negativi (downvotes)

---

### Dati dell'Autore (Utente)

* **author_name**: Nome dell'autore
* **user_is_verified**: Utente verificato (Sì/No)
* **user_account_created_time**: Data di creazione dell'account utente
* **user_awardee_karma**: Karma ricevuto tramite premi
* **user_awarder_karma**: Karma ottenuto assegnando premi ad altri
* **user_link_karma**: Karma accumulato dai link postati
* **user_comment_karma**: Karma accumulato dai commenti
* **user_total_karma**: Karma totale dell'utente

---

### Dati del Post (Thread)

* **post_id**: ID del post originale
* **post_score**: Punteggio del post
* **post_self_text**: Testo contenuto nel post originale
* **post_title**: Titolo del post
* **post_upvote_ratio**: Percentuale di voti positivi sul totale
* **post_thumbs_ups**: Numero di "mi piace" (pollici in su) del post
* **post_total_awards_received**: Numero totale di premi ricevuti dal post
* **post_created_time**: Orario di creazione del post

In [12]:
df_filtred = df[['comment_id', 'self_text', "post_self_text", "post_title"]]
df_filtred.head()

,comment_id,self_text,post_self_text,post_title
0,nwp6q7t,We import the poorest of the poor so they can ...,According to the Center for Immigration studie...,"The Minnesota Fraud Isn’t Just The Autism , Ch..."
1,nwp6p97,"Finally a decent map of Europe, where not hal...",NaN,Europe if all the glaciers melted – new cities...
2,nwp6eoj,&gt; Fundamentally the reason why China will n...,There is a high likelihood that in a few years...,CMV: If war were to begin in Taiwan against Ch...
3,nwp66r8,Evs have been around for 15 years,NaN,Do electric vehicles really catch fire more th...
4,nwp62hy,"Meanwhile, democrats are always praised for vo...",According to the Center for Immigration studie...,"The Minnesota Fraud Isn’t Just The Autism , Ch..."

* **comment_id**: ID del commento
* **self_text**: Testo del commento
* **post_self_text**: Testo contenuto nel post originale
* **post_title**: Titolo del post

In [14]:
df_filtred.head(10).to_csv("base.csv", index=False)